import type { Metadata } from "next";
import { QueryProvider } from "@/providers/query-provider";
import { SessionProvider } from "next-auth/react";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/auth";
import { ExitProvider } from "@/providers/exit-provider";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log("session:", session);
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={`${montserrat.className} antialiased container mx-auto`}>
          <QueryProvider>
            {children}
            <ExitProvider />
            <Toaster />
          </QueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
